# Механизм перевода
Engine=OpenCC
# Включенные методы ввода
EnabledIM=
# Профиль OpenCC для перехода с упрощенного на традиционный китайский
OpenCCS2TProfile=default
# Профиль OpenCC для перехода с традиционного на упрощенный китайский
OpenCCT2SProfile=default

[Hotkey]
0=Control+Shift+F

