# Вставить основное
PastePrimaryKey=
# Количество входов
Number of entries=5
# Не показывать пароль от менеджеров паролей
IgnorePasswordFromPasswordManager=False
# Отображать пароли в виде обычного текста
ShowPassword=False
# Секунд до сброса пароля
ClearPasswordAfter=30

[TriggerKey]
0=Control+semicolon

