# Определить текущее запущенное приложение (требуется перезапуск)
DetectApplication=True
# Пересылать ключевое событие вместо фиксации текста, если он не обрабатывается
PreferKeyEvent=True
# Поддерживать объект виртуальной клавиатуры для протокола V2 (Требуется перезапуск)
PersistentVirtualKeyboard=False

